// Field information for context pane - used for UI popups and documentation generation
const FIELD_INFO = {
  messageId: {
    label: 'Message ID',
    description: 'Unique identifier for this message.',
    technical: 'Generated by the extension when the message event fires in the page context.',
    filter: null
  },
  timestamp: {
    label: 'Timestamp',
    description: 'When the message was received.',
    technical: 'Captured from Date.now() when the message event fires in the page context.',
    filter: null
  },
  dataSize: {
    label: 'Size',
    description: 'Size of the message data when serialized.',
    technical: 'Calculated from JSON.stringify(event.data).length.',
    filter: null
  },
  buffered: {
    label: 'Buffered',
    description: 'Whether this message was captured before the panel connected.',
    technical: 'Messages sent before DevTools opens are buffered if the page was opened from a monitored tab.',
    filter: null
  },
  targetUrl: {
    label: 'Target URL',
    description: 'The full URL of the window that received this message.',
    technical: 'Obtained from window.location.href of the receiving frame.',
    filter: null
  },
  targetOrigin: {
    label: 'Target Origin',
    description: 'The origin of the window that received this message.',
    technical: 'Obtained from window.location.origin of the receiving frame.',
    filter: 'target:example.com'
  },
  targetTitle: {
    label: 'Target Title',
    description: 'The document title of the receiving window.',
    technical: 'Obtained from document.title of the receiving frame.',
    filter: null
  },
  targetFrame: {
    label: 'Target Frame',
    description: 'The Chrome frame ID of the receiving window.',
    technical: 'Obtained from sender.frameId in the background script.',
    filter: null
  },
  targetFrameError: {
    label: 'Target Frame Error',
    description: 'Error that occurred when trying to get frame information.',
    technical: 'Usually indicates the content script could not access frame APIs.',
    filter: null
  },
  sourceType: {
    label: 'Source Type',
    description: 'The relationship between the sender and receiver windows.',
    technical: 'Determined by comparing event.source to window.parent, window.opener, and child frames.',
    filter: 'sourceType:parent'
  },
  sourceOrigin: {
    label: 'Source Origin',
    description: 'The origin of the window that sent this message.',
    technical: 'Obtained from MessageEvent.origin. May be "null" for data: or file: URLs.',
    filter: 'source:example.com'
  },
  sourceFrame: {
    label: 'Source Frame',
    description: 'The Chrome frame ID of the sending window.',
    technical: 'Only currently supported when the message comes from window.parent. Obtained from chrome.webNavigation.getFrame in the background script.',
    filter: null
  },
  sourceIframeSrc: {
    label: 'Source iframe src',
    description: 'The src attribute of the iframe element that sent the message.',
    technical: 'Only available for child sources. Read from the iframe element in the parent document.',
    filter: null
  },
  sourceIframeId: {
    label: 'Source iframe id',
    description: 'The id attribute of the iframe element that sent the message.',
    technical: 'Only available for child sources. Read from the iframe element in the parent document.',
    filter: null
  },
  sourceIframeDomPath: {
    label: 'Source iframe path',
    description: 'CSS selector path to the iframe element that sent the message.',
    technical: 'Only available for child sources. Generated from the iframe element position in the DOM.',
    filter: null
  }
};
